### ISSUE TITLE
C2-12828-1  Issue/

### ISSUE THREAD

**Issue by zurez** [soywiz/vitaorganizer#13]
Any game directly transferred to memory card and installed works fine.
Any game installed through the vitaorganizer gives C2-12828-1 

Tried on Windows and Ubuntu
Vita fat model 1004

**Comment by soywiz** [comment]
Uhm. That's strange, it works fine for me. Are you using VitaShell 0.95?

**Comment by elshekar** [comment]
No problems here with Vitaorganizer 0.3 with Vitashell 0.95. I have to try the 0.4 but i dont think would be a problem

I remember that with another app, a week ago, failed with a game, but the cause was that this vpk was hand edited and the structure was not the original one

Please try with another games and as soywiz said, me sure you have the last vitashell

**Comment by zurez** [comment]
Yes, using VitaShell 0.95
Tried 4 games ,
size ranging from 70mb to 3 gb.
All games work perfect on direct install. Except 3 gb game for which I don't have space on memory card.
All games are from reddit/vitapiracy.
Games which didn't work are :
NFS Most Wanted(US Edition)
Mortal Kombat
Metal Slug.
* Have tried:
Multiple installs.
Rebuild database
Restore System
Format memory card.
Nothing seems to be working.
Any game which you have tested ?
P.S: Thank you for the replies. You guys are active.

**Comment by elshekar** [comment]
I'll do test back to home . Stay in tune

**Comment by soywiz** [comment]
I'll wait elshekar test.

**Comment by elshekar** [comment]
No problems here zurez with vitashell 1.0 henkaku 6 and vitaorganizer 0.4.Installed Senran Kagura (2GB) perfectly

Dont have Too much space but I can try the one of 70mb

By the way I didnt had problems with 0.91/0.95 henkaku r5 and 0.3

**Comment by soywiz** [comment]
Can you upload a video or something? Maybe watching it, we identify something different that causes the problem.

**Comment by zurez** [comment]
> I have done a fresh restore. i am trying to do everything afresh.
> Updated to latest Henkaku.
>VitaShell is @ v0.95
Lets hope. Is there a debug logging in vitaorhanizer?

**Comment by zurez** [comment]
Update: Doesn't work.
P.S: I think something corrupts the DB. My other games on Vita (NFS) which used to work before also start showing the error.

**Comment by zurez** [comment]
> So I used the One Step Method.
>Went to ux/organizer , Installed the vpk
Thats it. Doesn't works

**Comment by soywiz** [comment]
One step method, already installs the vpk, so you don't have to do anything more by yourself.

Also if you are using the two step method it is important to install the VPK first. Because installing the VPK wipes out all the data. So you will have to copy data later.

![options](https://cloud.githubusercontent.com/assets/570848/18607565/aeb469bc-7cd0-11e6-9d0c-409c90bb627b.png)

So if you have vitashell < 0.95, you have to:
* [on vita organizer] Send promoting VPK to PSVita
* [on device] Install it using vitashell
* [on vita organizer] Send Data to PSVita
It is important the order. If you send Data before ad later promoting to VPK. It won't work.

If you have vitashell 0.95:
* [on vita organizer] Send Full App to PSVita in just one 1-step (Requires VitaShell >= 0.95)
And that's it. It will work without doing anything else.

Since most people now have 0.95 or greater, I will remove the other options in this weekend's version as these can lead to misunderstandings.

**Comment by zurez** [comment]
managed to install a game . used the latest version. Thanks dev for such awesome utility.
