### ISSUE TITLE
Support fullgame/update vpks / separate files

### ISSUE THREAD

**Issue by soywiz** [soywiz/vitaorganizer#36]
Created a separated issue from this one: https://github.com/soywiz/vitaorganizer/issues/31

And is there any way to show on games list updates too? Eg i have 2 vpks 1 with base game v1.00 and second vpk with 1.1 update.

**Comment by gordon0001** [comment]
base game has the property CATEGORY to "gd" set (in param.sfo)
game updates do have "gp"as CATEGORY. take a look at vitashells package_installer.c
there you see how it handles gp
https://github.com/TheOfficialFloW/VitaShell/blob/master/package_installer.c#L85

**Comment by soywiz** [comment]
Cool! That's good to know. Thanks.
Right now I'm making the move to another town, so i won't have too much time to do this. Probably next week. Though I can merge with my phone if anyone does a PR implementing this.

**Comment by gordon0001** [comment]
alot has to be rewritten for this, because you are caching based on the game id. we need at least to use id, attribute, app_ver and category from param.sfo to differentiate vpks with the same game id.

havent started to work on it yet, all changes i make are pushed to the repo i forked in branch 'dev'. still far from finished, (excuse my style of coding, never heard of kotlin before, weird syntax compared to c++) but i backport important changes to your master branch when im happy with them and there are no bugs

**Comment by soywiz** [comment]
I think I'm going to cache based on file_path+size instead of gameid.

**Comment by soywiz** [comment]
And BTW: I'm here again. The move was pretty complex and I was three weeks without Internet and then I had lot of pending work.  Thank you very much for your contributions and keeping this active this time! :)
