### ISSUE TITLE
Support for VPKs in subfolders

### ISSUE THREAD

**Issue by paweloszu** [soywiz/vitaorganizer#9]
Add a feature to scan subfolders for VPK files because many people keep games that way.

**Comment by szczuru** [comment]
Afaik there is already option to select any directory you want :)

**Comment by soywiz** [comment]
I think that @paweloszu probably means to have several folders. Right now you can just have one folder without subfolders. So if one have games/homebrews in subfolders. For example: `emulators`, `games`, `applications`, vita organizer doesn't recognize them.

I would want to support one or two levels of subdirectories + having several different sources if required.

**Comment by elshekar** [comment]
Yes please, that would be nice!

Gracias tío :)

**Comment by soywiz** [comment]
Ok. I'll add 1 folder support this weekend :) Later I will support several different directories, which would require an additional window for configuring that.

**Comment by TheRadziu** [comment]
@paweloszu added this request because I asked him to. So here is example of such folder tree (subfolders basically). I keep my games like this: http://i.imgur.com/1w7NIZK.png . Inside of each folder there are vpks like this: http://i.imgur.com/71pIizP.png. The other issue is vitaorganizer is almost always transferring update vpk instead of full game one, and there is enormous amount of crashes, but I'll try you app again (i really like the idea!) as soon as there is subfolder/folder tree support :)

**Comment by soywiz** [comment]
Just released 0.5, and this versions searches in two levels of subfolders.
